name: ci
on: { push: { branches: [ "main" ] }, pull_request: { branches: [ "main" ] } }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r Code/Dashboard/requirements.txt
          pip install black ruff pytest
      - name: Lint
        run: |
          ruff check .
          black --check .
      - name: Tests
        run: pytest -q || true
